# Generated by Django 4.2.5 on 2023-09-15 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import horoscope.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Horoscope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horoscope', models.TextField(default='')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horoscopes_written', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportHoroscope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(default='')),
                ('reviewed', models.BooleanField(default=False)),
                ('reported_horoscope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horoscope.horoscope')),
            ],
        ),
        migrations.CreateModel(
            name='DailyHoroscope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('aquarius', models.ForeignKey(on_delete=horoscope.models.get_default_horoscope, related_name='+', to='horoscope.horoscope')),
                ('aries', models.ForeignKey(on_delete=horoscope.models.get_default_horoscope, related_name='+', to='horoscope.horoscope')),
                ('cancer', models.ForeignKey(on_delete=horoscope.models.get_default_horoscope, related_name='+', to='horoscope.horoscope')),
                ('capricorn', models.ForeignKey(on_delete=horoscope.models.get_default_horoscope, related_name='+', to='horoscope.horoscope')),
                ('gemini', models.ForeignKey(on_delete=horoscope.models.get_default_horoscope, related_name='+', to='horoscope.horoscope')),
                ('leo', models.ForeignKey(on_delete=horoscope.models.get_default_horoscope, related_name='+', to='horoscope.horoscope')),
                ('libra', models.ForeignKey(on_delete=horoscope.models.get_default_horoscope, related_name='+', to='horoscope.horoscope')),
                ('pisces', models.ForeignKey(on_delete=horoscope.models.get_default_horoscope, related_name='+', to='horoscope.horoscope')),
                ('sagittarius', models.ForeignKey(on_delete=horoscope.models.get_default_horoscope, related_name='+', to='horoscope.horoscope')),
                ('scorpio', models.ForeignKey(on_delete=horoscope.models.get_default_horoscope, related_name='+', to='horoscope.horoscope')),
                ('taurus', models.ForeignKey(on_delete=horoscope.models.get_default_horoscope, related_name='+', to='horoscope.horoscope')),
                ('virgo', models.ForeignKey(on_delete=horoscope.models.get_default_horoscope, related_name='+', to='horoscope.horoscope')),
            ],
        ),
    ]
